export const GET_DATA_BY_ID_STARTED = 'GET_DATA_BY_ID_STARTED';
export const GET_DATA_BY_ID_SUCCEED = 'GET_DATA_BY_ID_SUCCEED';
export const GET_DATA_BY_ID_FAILED = 'GET_DATA_BY_ID_FAILED';
export const GET_DATA_BY_ID_LOADED = 'GET_DATA_BY_ID_LOADED';
export const GO_BACK_TO_PAGE = 'GO_BACK_TO_PAGE';