export const GET_DATA_BY_PAGE_STARTED = 'GET_DATA_BY_PAGE_STARTED';
export const GET_DATA_BY_PAGE_SUCCEED = 'GET_DATA_BY_PAGE_SUCCEED';
export const GET_DATA_BY_PAGE_FAILED = 'GET_DATA_BY_PAGE_FAILED';
export const GET_DATA_BY_PAGE_LOADED = 'GET_DATA_BY_PAGE_LOADED';